"""added country origin column

Revision ID: 5bc0e52a321b
Revises: 1bec2636da85
Create Date: 2022-05-11 13:31:31.375854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc0e52a321b'
down_revision = '1bec2636da85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dessert', sa.Column('country_origin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dessert', 'country_origin')
    # ### end Alembic commands ###
