"""one-to-many back_populates

Revision ID: 6287f4a93f30
Revises: 
Create Date: 2022-05-11 08:46:51.309201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6287f4a93f30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dessert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('dessert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dessert_id'], ['dessert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('dessert')
    # ### end Alembic commands ###
