"""updated desserts

Revision ID: 8941d9d8bada
Revises: 3b5aa2d0b2f6
Create Date: 2022-11-09 14:15:04.389762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8941d9d8bada'
down_revision = '3b5aa2d0b2f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('would_order_again', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dessert', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('dessert', sa.Column('dessert_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dessert', 'dessert_type')
    op.drop_column('dessert', 'cost')
    op.drop_table('review')
    # ### end Alembic commands ###
