"""added review table and provided relationship

Revision ID: f32a4f731f79
Revises: 5bc0e52a321b
Create Date: 2022-05-11 13:48:12.254390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32a4f731f79'
down_revision = '5bc0e52a321b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('dessert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dessert_id'], ['dessert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
